### ISSUE TITLE
Is it possible to create and evolve schema on the fly?

### ISSUE THREAD

**Issue by alexeypetrushin** [traildb/traildb#127]
The TrailDB requires that schema (field names - `username, action`) should be created upfront

```
db = TrailDBConstructor('db', ['username', 'action'])

db.add(uuid, time, (username, action))
...
db.add(uuid, time, (username, action))
```

Would it be possible to avoid the schema declaration and let the DB itself **create it automatically, on the fly**? And also collect **events with the different structure**?

Something like:

```
# No schema declaration
db = TrailDBConstructor('db')

db.add(uuid, time, (username, action))
...
# there's 3 fields now and they have different names
db.add(uuid, time, (ip, cpu, mem))
```

Thanks!

**Comment by Noeda** [comment]
It's not possible to retroactively change the schema on the fly at this time while you are building the TrailDB. I think it would be difficult to implement right now given the design of TrailDB.

With regards to events with different structure what I think you might need to do is make a different TrailDB with different schema. This can get a bit convoluted but there's this feature called multicursors in TrailDB (look for `tdb_multi_cursor` in traildb.h and in tdb_types.h), which can let you iterate over more than one TrailDB so that you'll get events in the correct order, efficiently. If you keep track which TrailDB is in returned in each `tdb_multi_event` for each event you can iterate over mutiple TrailDBs that have different schemas.

You'll have easier time if you are willing to just have all possible fields in single TrailDB.

**Comment by alexeypetrushin** [comment]
Thanks!
